"""Connector development kit: a new tool in minutes, and it cannot be merged until it behaves like the others.

``python -m soc_platform connector new <name> --category edr --tool "Vendor Product"`` writes

* ``soc_platform/connectors/tools/<name>.py``  - a working connector that already follows the sync rules (time-watermark
  resume, a page token only within one sync, ``need()`` for the record id, tolerant of missing fields, a declared
  setting for every value it reads, a health stream)
* ``soc_platform/fixtures/<name>.json``        - fake-mode responses in the vendor's shape (replace with real ones)
* ``soc_platform/tests/test_connector_<name>.py`` - its paging-and-resume test
* an entry in ``config/connectors.yaml``         - switched off, stage ``fake``

``python -m soc_platform connector check <name>`` then runs everything that applies to it: its own test and the shared
conformance suite (paging coverage, throttling, token renewal, missing permissions, every field removed or null).
Edit the endpoint paths, fields and fixtures to the vendor's API; ``check`` tells you what is still wrong.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CATEGORIES = ("edr", "email", "identity", "dns", "deception", "pam", "vuln", "cloud", "intel", "itsm", "cmdb", "siem")
DIMENSIONS = {"edr": "endpoint", "email": "email", "identity": "identity", "dns": "dns", "deception": "deception",
              "pam": "privileged_access", "vuln": "vulnerability", "cloud": "cloud", "intel": "threat_intel",
              "itsm": "other", "cmdb": "other", "siem": "other"}
_NAME = re.compile(r"^[a-z][a-z0-9_]{1,39}$")

CONNECTOR = '''"""{tool} connector (generated by `python -m soc_platform connector new`; adapt it to the vendor's API).

Read: {stream} (events, resumed from the newest change time). Write: none yet - add actions with ``ConnectorAction``.
To confirm with the client: API account, read permission, rate limits.
"""

from __future__ import annotations

from typing import Any

from soc_platform.connectors.base import Page
from soc_platform.connectors.http import ApiKeyHeader, HttpTransport
from soc_platform.connectors.registry import ConfigField, ConnectorManifest
from soc_platform.connectors.tools._common import ToolConnector, Watermark, need, parse_ts
from soc_platform.core.identity import user_ref
from soc_platform.core.schema import EntityRef, NormalizedRecord

SEVERITY = {{"1": "low", "2": "medium", "3": "high", "4": "critical", "low": "low", "medium": "medium", "high": "high",
            "critical": "critical"}}


class {cls}(ToolConnector):
    name = "{name}"
    tool = "{tool}"
    dimension = "{dimension}"
    streams = ("{stream}",)
    read_scopes = ("<the vendor's read permission for events>",)
    page_size = 100

    def fetch_page(self, stream: str, cursor: str | None) -> Page:
        if stream != "{stream}":
            raise ValueError(f"unknown stream {{stream}}")
        # Between syncs the cursor is "since:<newest change time seen>"; within one sync "<page token>|<since>".
        # Never keep a page token as the next sync's start: tokens expire.
        token, _, since = (cursor or "").partition("|")
        wm = Watermark.of(self, stream)
        if not cursor or cursor.startswith("since:"):
            since, token = wm.start(cursor) or "", ""
        params: dict[str, Any] = {{"limit": self.page_size}}
        if since:
            params["updated_since"] = since
        if token:
            params["page_token"] = token
        body = self.get("/api/v1/events", params=params)
        recs = body.get("items") or []
        wm.see(recs, "updated_at")
        nxt = body.get("next_page_token")
        if nxt and recs:
            return Page(recs, f"{{nxt}}|{{since}}", has_more=True)
        return Page(recs, wm.finish(), has_more=False, reset=True)

    def normalize(self, stream: str, raw: dict[str, Any]) -> list[NormalizedRecord]:
        host = raw.get("host") or {{}}
        refs = []
        if host.get("hostname") or host.get("ip"):
            refs.append(EntityRef(kind="asset", role="host", attributes={{"hostname": host.get("hostname"),
                                                                          "ip": host.get("ip")}}))
        user = user_ref(raw.get("user"), default_domain=self.settings.get("user_domain"))
        if user is not None:
            refs.append(user)
        return [NormalizedRecord(
            kind="alert", tool=self.tool, source_type="event", source_id=need(raw, "id"),
            observed_at=parse_ts(raw.get("updated_at") or raw.get("created_at")), dimension=self.dimension,
            title=raw.get("title") or "{tool} event", severity=SEVERITY.get(str(raw.get("severity") or "").lower(), "low"),
            refs=refs, attributes={{"status": raw.get("status"), "category": raw.get("category")}})]


def _live(s: dict[str, Any]) -> HttpTransport:
    return HttpTransport(s["base_url"], ApiKeyHeader("Authorization", s["api_key"], "Bearer "))


MANIFEST = ConnectorManifest(
    name="{name}", tool="{tool}", vendor="{vendor}", category="{category}", dimension="{dimension}",
    description="{tool} events.",
    factory=lambda s, t: {cls}(s, t, rate_per_sec=2, burst=4), live_transport=_live,
    config=[ConfigField("base_url", "API base URL", kind="url"),
            ConfigField("api_key", "API key", secret=True),
            ConfigField("user_domain", "UPN suffix for bare user names", required=False)],
    confidence="Unknown", to_confirm="API account and read permission; rate limits",
    fake_settings={{"base_url": "https://api.example.invalid", "user_domain": "acme-demo.com"}},
    focus_areas=("incident",),
)
'''

TEST = '''"""Paging and resume for the {name} connector (generated). The shared suite in test_connector_conformance.py also
runs throttling, token renewal, missing-permission and missing-field checks on it automatically."""

from soc_platform.tests.test_connector_conformance import asked_from, at_least, calls_to, demo_route, fresh, reroute, stamp, sync

# read by the shared coverage test: every stream of every connector needs a paging test
PAGING_TESTED = {{("{name}", "{stream}")}}


def test_{name}_pages_with_tokens_and_resumes_from_the_newest_update(session):
    src = demo_route("{name}", "GET", "/api/v1/events")
    items = at_least(src["body"]["items"])
    newest = stamp(items, "updated_at")
    routes = [{{**src, "times": 1, "body": {{"items": items[:2], "next_page_token": "p2"}}}},
              {{**src, "body": {{"items": items[2:]}}}}]
    conn = fresh("{name}", routes)
    rep, cp = sync(session, conn, "{stream}")
    assert not rep.errors and rep.ingested == len(items), rep.errors
    assert calls_to(conn.http, "/api/v1/events", "GET")[1]["params"]["page_token"] == "p2"
    assert cp.cursor == f"since:{{newest}}"                     # resumes from a time, never from a page token
    t = reroute(conn, routes)
    sync(session, conn, "{stream}")
    assert calls_to(t, "/api/v1/events", "GET")[0]["params"]["updated_since"] == asked_from(newest)
'''


def _fixture(name: str, tool: str) -> dict:
    items = [{"id": f"{name}-evt-{i}", "title": f"{tool} sample alert {i}", "severity": sev, "status": "new",
              "category": "sample", "created_at": f"2026-09-20T0{i}:00:00Z", "updated_at": f"2026-09-20T0{i}:05:00Z",
              "host": {"hostname": "JANE-LT01", "ip": "10.20.1.15"}, "user": "jane.doe"}
             for i, sev in ((1, "low"), (2, "medium"))]
    return {"routes": [{"method": "GET", "path": r"^/api/v1/events$", "status": 200,
                        "body": {"items": items, "next_page_token": None}}]}


def scaffold(name: str, category: str, tool: str = "", vendor: str = "", *, root: Path = ROOT,
             add_to_config: bool = True) -> list[Path]:
    """Write the connector, its fixtures, its test and a switched-off config entry. Returns the files written."""
    if not _NAME.match(name):
        raise ValueError("name: lower-case letters, digits and _ (2-40 characters), starting with a letter")
    if category not in CATEGORIES:
        raise ValueError(f"category must be one of {', '.join(CATEGORIES)}")
    from soc_platform.connectors.registry import discover

    if root == ROOT and name in discover():
        raise ValueError(f"a connector named {name!r} already exists")
    tool = tool or name.replace("_", " ").title()
    vendor = vendor or tool.split()[0]
    cls = "".join(w.capitalize() for w in name.split("_")) + "Connector"
    ctx = {"name": name, "tool": tool.replace('"', "'"), "vendor": vendor.replace('"', "'"), "category": category,
           "dimension": DIMENSIONS[category], "cls": cls, "stream": "events"}
    files = {root / "soc_platform" / "connectors" / "tools" / f"{name}.py": CONNECTOR.format(**ctx),
             root / "soc_platform" / "fixtures" / f"{name}.json": json.dumps(_fixture(name, ctx["tool"]), indent=1) + "\n",
             root / "soc_platform" / "tests" / f"test_connector_{name}.py": TEST.format(**ctx)}
    for path in files:
        if path.exists():
            raise ValueError(f"{path} already exists - nothing was written")
    for path, text in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    written = list(files)
    cfg = root / "config" / "connectors.yaml"
    if add_to_config and cfg.exists():
        with cfg.open("a", encoding="utf-8") as fh:
            fh.write(f"  {name}:   # {ctx['tool']} - {category}; generated, switched off until it passes "
                     f"`connector check` and a preflight\n    enabled: false\n    stage: fake\n    settings:\n"
                     f"      base_url: \"${{{name.upper()}_BASE_URL}}\"\n"
                     f"      api_key: \"${{{name.upper()}_API_KEY}}\"   # SECRET\n")
        written.append(cfg)
    return written


def check(name: str) -> int:
    """Run every test that applies to one connector; returns pytest's exit code (0 = it conforms)."""
    tests = ROOT / "soc_platform" / "tests"
    files = [str(tests / "test_connector_conformance.py"), str(tests / "test_connectors.py")]
    own = tests / f"test_connector_{name}.py"
    if own.exists():
        files.append(str(own))
    return subprocess.call([sys.executable, "-m", "pytest", *files, "-q", "-p", "no:cacheprovider",
                            "-k", f"{name} or every_connector_stream or every_tool"], cwd=ROOT)
